"""empty message

Revision ID: 0f6b5b5138df
Revises: fa66b073e7cc
Create Date: 2023-01-26 22:34:22.876009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6b5b5138df'
down_revision = 'fa66b073e7cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end', sa.DateTime(), nullable=True))
        batch_op.alter_column('start',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Appointment', schema=None) as batch_op:
        batch_op.alter_column('start',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('end')

    # ### end Alembic commands ###
