"""empty message

Revision ID: 6596a74ea7a2
Revises: ef319259b3e3
Create Date: 2023-01-25 18:17:49.585274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6596a74ea7a2'
down_revision = 'ef319259b3e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Appointment', schema=None) as batch_op:
        batch_op.alter_column('start',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('end',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('birthday')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('Appointment', schema=None) as batch_op:
        batch_op.alter_column('end',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('start',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
